module.exports = {
  roles_page_1: [ {
    name: 'myRole-1',
    id: 'myRoleId-1',
    description: 'myDescription-1'
  }, {
    name: 'myRole-2',
    id: 'myRoleId-2',
    description: 'myDescription-2'
  }, {
    name: 'myRole-3',
    id: 'myRoleId-3',
    description: 'myDescription-3'
  }, {
    name: 'myRole-4',
    id: 'myRoleId-4',
    description: 'myDescription-4'
  }, {
    name: 'myRole-5',
    id: 'myRoleId-5',
    description: 'myDescription-5'
  }, {
    name: 'myRole-6',
    id: 'myRoleId-6',
    description: 'myDescription-6'
  }, {
    name: 'myRole-7',
    id: 'myRoleId-7',
    description: 'myDescription-7'
  }, {
    name: 'myRole-8',
    id: 'myRoleId-8',
    description: 'myDescription-8'
  }, {
    name: 'myRole-9',
    id: 'myRoleId-9',
    description: 'myDescription-9'
  }, {
    name: 'myRole-10',
    id: 'myRoleId-10',
    description: 'myDescription-10'
  }, {
    name: 'myRole-11',
    id: 'myRoleId-11',
    description: 'myDescription-11'
  }, {
    name: 'myRole-12',
    id: 'myRoleId-12',
    description: 'myDescription-12'
  }, {
    name: 'myRole-13',
    id: 'myRoleId-13',
    description: 'myDescription-13'
  }, {
    name: 'myRole-14',
    id: 'myRoleId-14',
    description: 'myDescription-14'
  }, {
    name: 'myRole-15',
    id: 'myRoleId-15',
    description: 'myDescription-15'
  }, {
    name: 'myRole-16',
    id: 'myRoleId-16',
    description: 'myDescription-16'
  }, {
    name: 'myRole-17',
    id: 'myRoleId-17',
    description: 'myDescription-17'
  }, {
    name: 'myRole-18',
    id: 'myRoleId-18',
    description: 'myDescription-18'
  }, {
    name: 'myRole-19',
    id: 'myRoleId-19',
    description: 'myDescription-19'
  }, {
    name: 'myRole-20',
    id: 'myRoleId-20',
    description: 'myDescription-20'
  }, {
    name: 'myRole-21',
    id: 'myRoleId-21',
    description: 'myDescription-21'
  }, {
    name: 'myRole-22',
    id: 'myRoleId-22',
    description: 'myDescription-22'
  }, {
    name: 'myRole-23',
    id: 'myRoleId-23',
    description: 'myDescription-23'
  }, {
    name: 'myRole-24',
    id: 'myRoleId-24',
    description: 'myDescription-24'
  }, {
    name: 'myRole-25',
    id: 'myRoleId-25',
    description: 'myDescription-25'
  }, {
    name: 'myRole-26',
    id: 'myRoleId-26',
    description: 'myDescription-26'
  }, {
    name: 'myRole-27',
    id: 'myRoleId-27',
    description: 'myDescription-27'
  }, {
    name: 'myRole-28',
    id: 'myRoleId-28',
    description: 'myDescription-28'
  }, {
    name: 'myRole-29',
    id: 'myRoleId-29',
    description: 'myDescription-29'
  }, {
    name: 'myRole-30',
    id: 'myRoleId-30',
    description: 'myDescription-30'
  }, {
    name: 'myRole-31',
    id: 'myRoleId-31',
    description: 'myDescription-31'
  }, {
    name: 'myRole-32',
    id: 'myRoleId-32',
    description: 'myDescription-32'
  }, {
    name: 'myRole-33',
    id: 'myRoleId-33',
    description: 'myDescription-33'
  }, {
    name: 'myRole-34',
    id: 'myRoleId-34',
    description: 'myDescription-34'
  }, {
    name: 'myRole-35',
    id: 'myRoleId-35',
    description: 'myDescription-35'
  }, {
    name: 'myRole-36',
    id: 'myRoleId-36',
    description: 'myDescription-36'
  }, {
    name: 'myRole-37',
    id: 'myRoleId-37',
    description: 'myDescription-37'
  }, {
    name: 'myRole-38',
    id: 'myRoleId-38',
    description: 'myDescription-38'
  }, {
    name: 'myRole-39',
    id: 'myRoleId-39',
    description: 'myDescription-39'
  }, {
    name: 'myRole-40',
    id: 'myRoleId-40',
    description: 'myDescription-40'
  }, {
    name: 'myRole-41',
    id: 'myRoleId-41',
    description: 'myDescription-41'
  }, {
    name: 'myRole-42',
    id: 'myRoleId-42',
    description: 'myDescription-42'
  }, {
    name: 'myRole-43',
    id: 'myRoleId-43',
    description: 'myDescription-43'
  }, {
    name: 'myRole-44',
    id: 'myRoleId-44',
    description: 'myDescription-44'
  }, {
    name: 'myRole-45',
    id: 'myRoleId-45',
    description: 'myDescription-45'
  }, {
    name: 'myRole-46',
    id: 'myRoleId-46',
    description: 'myDescription-46'
  }, {
    name: 'myRole-47',
    id: 'myRoleId-47',
    description: 'myDescription-47'
  }, {
    name: 'myRole-48',
    id: 'myRoleId-48',
    description: 'myDescription-48'
  }, {
    name: 'myRole-49',
    id: 'myRoleId-49',
    description: 'myDescription-49'
  }, {
    name: 'myRole-50',
    id: 'myRoleId-50',
    description: 'myDescription-50'
  } ],
  roles_page_2: [ {
    name: 'myRole-51',
    id: 'myRoleId-51',
    description: 'myDescription-51'
  }, {
    name: 'myRole-52',
    id: 'myRoleId-52',
    description: 'myDescription-52'
  }, {
    name: 'myRole-53',
    id: 'myRoleId-53',
    description: 'myDescription-53'
  }, {
    name: 'myRole-54',
    id: 'myRoleId-54',
    description: 'myDescription-54'
  }, {
    name: 'myRole-55',
    id: 'myRoleId-55',
    description: 'myDescription-55'
  }, {
    name: 'myRole-56',
    id: 'myRoleId-56',
    description: 'myDescription-56'
  }, {
    name: 'myRole-57',
    id: 'myRoleId-57',
    description: 'myDescription-57'
  }, {
    name: 'myRole-58',
    id: 'myRoleId-58',
    description: 'myDescription-58'
  }, {
    name: 'myRole-59',
    id: 'myRoleId-59',
    description: 'myDescription-59'
  }, {
    name: 'myRole-60',
    id: 'myRoleId-60',
    description: 'myDescription-60'
  }, {
    name: 'myRole-61',
    id: 'myRoleId-61',
    description: 'myDescription-61'
  }, {
    name: 'myRole-62',
    id: 'myRoleId-62',
    description: 'myDescription-62'
  }, {
    name: 'myRole-63',
    id: 'myRoleId-63',
    description: 'myDescription-63'
  }, {
    name: 'myRole-64',
    id: 'myRoleId-64',
    description: 'myDescription-64'
  }, {
    name: 'myRole-65',
    id: 'myRoleId-65',
    description: 'myDescription-65'
  }, {
    name: 'myRole-66',
    id: 'myRoleId-66',
    description: 'myDescription-66'
  }, {
    name: 'myRole-67',
    id: 'myRoleId-67',
    description: 'myDescription-67'
  }, {
    name: 'myRole-68',
    id: 'myRoleId-68',
    description: 'myDescription-68'
  }, {
    name: 'myRole-69',
    id: 'myRoleId-69',
    description: 'myDescription-69'
  }, {
    name: 'myRole-70',
    id: 'myRoleId-70',
    description: 'myDescription-70'
  }, {
    name: 'myRole-71',
    id: 'myRoleId-71',
    description: 'myDescription-71'
  }, {
    name: 'myRole-72',
    id: 'myRoleId-72',
    description: 'myDescription-72'
  }, {
    name: 'myRole-73',
    id: 'myRoleId-73',
    description: 'myDescription-73'
  }, {
    name: 'myRole-74',
    id: 'myRoleId-74',
    description: 'myDescription-74'
  }, {
    name: 'myRole-75',
    id: 'myRoleId-75',
    description: 'myDescription-75'
  }, {
    name: 'myRole-76',
    id: 'myRoleId-76',
    description: 'myDescription-76'
  }, {
    name: 'myRole-77',
    id: 'myRoleId-77',
    description: 'myDescription-77'
  }, {
    name: 'myRole-78',
    id: 'myRoleId-78',
    description: 'myDescription-78'
  }, {
    name: 'myRole-79',
    id: 'myRoleId-79',
    description: 'myDescription-79'
  }, {
    name: 'myRole-80',
    id: 'myRoleId-80',
    description: 'myDescription-80'
  } ]
};
